// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/grades/:gradeId/topics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grades/[gradeId]/topics.get').default>>>>
    }
    '/api/grades': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grades/index.get').default>>>>
    }
    '/api/practice/answer': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/practice/answer.post').default>>>>
    }
    '/api/practice/daily': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/practice/daily.get').default>>>>
    }
    '/api/practice/questions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/practice/questions.get').default>>>>
    }
    '/api/practice/wrong-book': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/practice/wrong-book.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.2_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@3.21.2_@parcel+w_8aa72e5c369d1bbd6ab9810afefa816a/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}