// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/25/2026, 4:02:40 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/lomiushuk/olympiad-math/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lomiushuk/olympiad-math/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lomiushuk/olympiad-math/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lomiushuk/olympiad-math/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lomiushuk/olympiad-math/web/plugins/**/*.{js,ts,mjs}","/Users/lomiushuk/olympiad-math/web/composables/**/*.{js,ts,mjs}","/Users/lomiushuk/olympiad-math/web/utils/**/*.{js,ts,mjs}","/Users/lomiushuk/olympiad-math/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lomiushuk/olympiad-math/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lomiushuk/olympiad-math/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lomiushuk/olympiad-math/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;